In [1]:
import pandas as pd
df = pd.read_csv('D:\dummy project\Bank Personal Loan Modeling\Bank_Personal_Loan_Modelling.csv')

In [2]:
df.head()

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
0,1,25,1,49,91107,4,1.6,1,0,0,1,0,0,0
1,2,45,19,34,90089,3,1.5,1,0,0,1,0,0,0
2,3,39,15,11,94720,1,1.0,1,0,0,0,0,0,0
3,4,35,9,100,94112,1,2.7,2,0,0,0,0,0,0
4,5,35,8,45,91330,4,1.0,2,0,0,0,0,0,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  5000 non-null   int64
 1   Age                 5000 non-null   int64
 2   Experience          5000 non-null   int64
 3   Income              5000 non-null   int64
 4   ZIP Code            5000 non-null   int64
 5   Family              5000 non-null   int64
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64
 8   Mortgage            5000 non-null   int64
 9   Personal Loan       5000 non-null   int64
 10  Securities Account  5000 non-null   int64
 11  CD Account          5000 non-null   int64
 12  Online              5000 non-null   int64
 13  CreditCard          5000 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 547.0 KB

In [4]:
df.describe(include='all')

,ID,Age,Experience,Income,ZIP Code,Family,CCAvg,Education,Mortgage,Personal Loan,Securities Account,CD Account,Online,CreditCard
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,2500.500000,45.338400,20.104600,73.774200,93152.503000,2.396400,1.937938,1.881000,56.498800,0.096000,0.104400,0.06040,0.596800,0.294000
std,1443.520003,11.463166,11.467954,46.033729,2121.852197,1.147663,1.747659,0.839869,101.713802,0.294621,0.305809,0.23825,0.490589,0.455637
min,1.000000,23.000000,-3.000000,8.000000,9307.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
25%,1250.750000,35.000000,10.000000,39.000000,91911.000000,1.000000,0.700000,1.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000
50%,2500.500000,45.000000,20.000000,64.000000,93437.000000,2.000000,1.500000,2.000000,0.000000,0.000000,0.000000,0.00000,1.000000,0.000000
75%,3750.250000,55.000000,30.000000,98.000000,94608.000000,3.000000,2.500000,3.000000,101.000000,0.000000,0.000000,0.00000,1.000000,1.000000
max,5000.000000,67.000000,43.000000,224.000000,96651.000000,4.000000,10.000000,3.000000,635.000000,1.000000,1.000000,1.00000,1.000000,1.000000

In [5]:
df.isnull().sum()

ID                    0
Age                   0
Experience            0
Income                0
ZIP Code              0
Family                0
CCAvg                 0
Education             0
Mortgage              0
Personal Loan         0
Securities Account    0
CD Account            0
Online                0
CreditCard            0
dtype: int64

In [25]:
# Menghitung total baris duplikat
print("Jumlah baris duplikat:", df.duplicated().sum())

Jumlah baris duplikat: 0

In [6]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [7]:
df.columns

Index(['id', 'age', 'experience', 'income', 'zip_code', 'family', 'ccavg',
       'education', 'mortgage', 'personal_loan', 'securities_account',
       'cd_account', 'online', 'creditcard'],
      dtype='object')

ubah label education menjadi teks

In [9]:
labels = {1: 'Undergraduate', 2: 'Graduate', 3: 'Professional'}
df['education_group'] = df['education'].map(labels)
df[['education', 'education_group']].head(10)

   education education_group
0          1   Undergraduate
1          1   Undergraduate
2          1   Undergraduate
3          2        Graduate
4          2        Graduate
5          2        Graduate
6          2        Graduate
7          3    Professional
8          2        Graduate
9          3    Professional

Segmentasi Umur dan Pendapatan

In [11]:
labels_age = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels_age)
df[['age', 'age_group']].head(10)

   age    age_group
0   25  Young Adult
1   45        Adult
2   39        Adult
3   35  Young Adult
4   35  Young Adult
5   37        Adult
6   53  Middle-aged
7   50  Middle-aged
8   35  Young Adult
9   34  Young Adult

In [12]:
labels_income = ['Low Income', 'Medium Income', 'High Income']
df['income_group'] = pd.qcut(df['income'], q=3, labels = labels_income)
df[['income', 'income_group']].head(10)

   income   income_group
0      49  Medium Income
1      34     Low Income
2      11     Low Income
3     100    High Income
4      45  Medium Income
5      29     Low Income
6      72  Medium Income
7      22     Low Income
8      81  Medium Income
9     180    High Income

Status KPR memisahkan yang punya dan tidak punta

In [15]:
df['has_mortgage'] = df['mortgage'].apply(lambda x: 'Has Mortgage' if x > 0 else 'No Mortgage')
df[['mortgage', 'has_mortgage']].head(10)

   mortgage  has_mortgage
0         0   No Mortgage
1         0   No Mortgage
2         0   No Mortgage
3         0   No Mortgage
4         0   No Mortgage
5       155  Has Mortgage
6         0   No Mortgage
7         0   No Mortgage
8       104  Has Mortgage
9         0   No Mortgage

In [16]:
df.columns

Index(['id', 'age', 'experience', 'income', 'zip_code', 'family', 'ccavg',
       'education', 'mortgage', 'personal_loan', 'securities_account',
       'cd_account', 'online', 'creditcard', 'education_group', 'age_group',
       'income_group', 'has_mortgage'],
      dtype='object')

In [20]:
from sqlalchemy import create_engine

# Step 1 : Connect to PostgreSQL 
# Replace placeholders with your actual details
username = "postgres"
password = "260105"
host = "localhost"
port = "5432"
database = "bank_loan"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

#Step 2 : Load DataFrame into PostgreSQL
table_name = "bankloan"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'bankloan' in database 'bank_loan'.